export interface Article {
    id : any,
    author : string,
    title : string,
    text : string,
    subtitle : string,
    draft : boolean,
    cover : any,
    coverImg : string,
    coverDescription : string,
    disableComments : boolean,
    hideLikesCount : boolean,
    hideAuthor : boolean,
    hideViewsCount : boolean,
    hideDate : boolean,
    tags : string[],
    moreArticles : any,
    surveys : any,
  }