# Generated by Django 3.2.3 on 2021-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('draft', models.BooleanField(default=True)),
                ('hideAuthor', models.BooleanField(default=True)),
                ('disableComments', models.BooleanField(default=False)),
                ('hideLikesCount', models.BooleanField(default=False)),
                ('hideViewsCount', models.BooleanField(default=False)),
                ('hideDate', models.BooleanField(default=False)),
                ('moreArticles', models.TextField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
