# Generated by Django 3.2.3 on 2021-09-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0004_survey_variant_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
