# Generated by Django 3.2.3 on 2021-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0005_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='article',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='variant',
            name='survey',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vote',
            name='variant',
            field=models.TextField(default=''),
        ),
    ]
