# Generated by Django 3.2.3 on 2021-09-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0010_comment_profileurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profileUrl',
            new_name='photoURL',
        ),
    ]
