# Generated by Django 3.2.3 on 2021-09-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0012_article_activatearticleswithsametopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(null=True)),
                ('user', models.TextField(null=True)),
            ],
        ),
    ]
