# Generated by Django 3.2.3 on 2021-09-19 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0013_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(null=True)),
                ('user', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='view',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
