# Generated by Django 3.2.3 on 2021-09-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0014_auto_20210919_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='removable',
        ),
    ]
