# Generated by Django 3.2.3 on 2021-09-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0015_remove_list_removable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='activateArticlesWithSameTopic',
        ),
    ]
