# Generated by Django 3.2.3 on 2021-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0016_remove_article_activatearticleswithsametopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('removeDate', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
