# Generated by Django 3.2.3 on 2021-10-06 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0018_rename_removedate_ad_apparitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
