# Generated by Django 3.2.3 on 2021-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0020_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='neldenable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
