# Generated by Django 3.2.3 on 2021-10-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estcurier', '0023_remove_article_unlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='coverDescription',
            field=models.TextField(default=''),
        ),
    ]
